# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb17fb9840900b3718b46f8f3bf1a78f0618614463405afa0975db589988d544c5cb59021f0a67d91366a94d78963eeb27c96a49f9a89f1c6368b85f57b61d5

test:
  secret_key_base: c44ca0323079152d177d7eba0eeb26b27e0e51bb67671ee29b564905b9e407e999ebad5c084bf0a4c275bcda8a148a20806cbb283f4ad9c2bc842105a096015d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
